### PR TITLE
Implement offline (air-gapped) mode

### PR DESCRIPTION
**Pull request by evgkrsk**
See: https://github.com/devopstales/trivy-operator/issues/28

### CODE REVIEW

**Comment by devopstales** [comment]
@evgkrsk please check the conflicts with this commit: https://github.com/devopstales/trivy-operator/commit/a79a7ed7a623ca823651132b9ee55ac0a00a0e5f

**Comment by evgkrsk** [comment]
I see no sense in https://github.com/devopstales/trivy-operator/commit/a79a7ed7a623ca823651132b9ee55ac0a00a0e5f
 as long as TRIVY_SKIP_DB_UPDATE in this PR is already makes trivy skip DB update.

**Comment by evgkrsk** [comment]
I vote to revert a79a7ed7a623ca823651132b9ee55ac0a00a0e5f . What do you think?

**Comment by devopstales** [comment]
@evgkrsk If you read the link I give you at the commithttps://github.com/devopstales/trivy-operator/commit/a79a7ed7a623ca823651132b9ee55ac0a00a0e5f, you can see, that you need to disable update db not just in the start but every image scan. In my commit I created an example for you, you can add an option for the scan based on an environment variable. Use this example to add the `--skip-update` option for the scans.

**Comment by evgkrsk** [comment]
There is not need to do this: https://aquasecurity.github.io/trivy/v0.31.3/docs/references/customization/envs/

TRIVY_SKIP_DB_UPDATE in this PR already must be translated to "--skip-db-update" by trivy binary.

**Comment by evgkrsk** [comment]
Ok, I will rewrite PR over this commit...

**Pull request merged**
